server:
  port: 80

spring:
  application:
    name: hermesPlus
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/hermesPlus
    username: root
    password: r1r2r3
    hikari:
      connection-init-sql: SELECT 1
      minimum-idle: 2
      maximum-pool-size: 4
mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true