server:
  port: 81
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://3.39.248.124:3306/hermes
    username: admin
    password: qwer!@#$
    hikari:
      connection-init-sql: SELECT 1
      minimum-idle: 2
      maximum-pool-size: 4

mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:log4j.xml