SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS ADDRESS_INFO;
DROP TABLE IF EXISTS VISIT_INFO;
DROP TABLE IF EXISTS USER_INFO;
DROP TABLE IF EXISTS GRADE_INFO;




/* Create Tables */

CREATE TABLE ADDRESS_INFO
(
	AI_NUM int NOT NULL AUTO_INCREMENT,
	AI_PLACE_NAME varchar(20) NOT NULL,
	-- Recipient
	AI_RECIPENT_NAME varchar(30) NOT NULL COMMENT 'Recipient',
	AI_PHONE varchar(30) NOT NULL,
	AI_ADDRESS varchar(500) NOT NULL,
	UI_NUM int NOT NULL,
	PRIMARY KEY (AI_NUM)
);


CREATE TABLE GRADE_INFO
(
	-- 회원등급
	GI_NUM int NOT NULL AUTO_INCREMENT COMMENT '회원등급',
	GI_NAME char(10) NOT NULL,
	GI_DESC varchar(100),
	GI_ORDER int,
	PRIMARY KEY (GI_NUM)
);


CREATE TABLE USER_INFO
(
	UI_NUM int NOT NULL AUTO_INCREMENT,
	UI_FIRST_NAME varchar(50) NOT NULL,
	UI_LAST_NAME varchar(50) NOT NULL,
	UI_EMAIL varchar(255) NOT NULL,
	UI_PHONE varchar(50) NOT NULL,
	UI_PWD varchar(30) NOT NULL,
	UI_GENDER char(1) NOT NULL,
	UI_BIRTH char(8),
	UI_ADDRESS varchar(500) NOT NULL,
	UI_DORMANT char(1) DEFAULT '0' NOT NULL,
	UI_OUT char(1) DEFAULT '0' NOT NULL,
	UI_TYPE char(1) DEFAULT '1' NOT NULL,
	CREDAT char(8) DEFAULT 'DATE_FORMAT (NOW(), ''%Y%m%d'')' NOT NULL,
	CRETIM char(6) DEFAULT 'DATE_FORMAT (NOW(), ''%H%i%s'')' NOT NULL,
	-- 회원등급
	GI_NUM int NOT NULL COMMENT '회원등급',
	PRIMARY KEY (UI_NUM),
	UNIQUE (UI_EMAIL)
);


CREATE TABLE VISIT_INFO
(
	VI_NUM int NOT NULL AUTO_INCREMENT,
	VI_IP varchar(39) NOT NULL,
	VI_VISIT_DATE timestamp NOT NULL,
	UI_NUM int NOT NULL,
	PRIMARY KEY (VI_NUM)
);



/* Create Foreign Keys */

ALTER TABLE USER_INFO
	ADD FOREIGN KEY (GI_NUM)
	REFERENCES GRADE_INFO (GI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ADDRESS_INFO
	ADD FOREIGN KEY (UI_NUM)
	REFERENCES USER_INFO (UI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE VISIT_INFO
	ADD FOREIGN KEY (UI_NUM)
	REFERENCES USER_INFO (UI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



